name: Test Workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test Upload
        uses: actions/upload-artifact@v2
        with:
          name: test-file
          path: README.md
