name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy-client:
    name: Deploy Client
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Client Deployment
        run: |
          curl -X POST "https://api.render.com/v1/services/YOUR_CLIENT_SERVICE_ID/deploys" \
            -H "Accept: application/json" \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}"

  deploy-server:
    name: Deploy Server
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Server Deployment
        run: |
          curl -X POST "https://api.render.com/v1/services/YOUR_SERVER_SERVICE_ID/deploys" \
            -H "Accept: application/json" \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}"
