name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy-client:
    name: Deploy Client
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Client Deployment
        run: |
          curl -X POST "https://api.render.com/v1/services/srv-cttf1mt2ng1s73c8ph5g/deploys" \
            -H "Accept: application/json" \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}"

  deploy-server:
    name: Deploy Server
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Server Deployment
        run: |
          curl -X POST "https://api.render.com/v1/services/srv-cttf38popnds73ccao6g/deploys" \
            -H "Accept: application/json" \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}"
